### PR TITLE
Fixes #91

### LINKED ISSUE #91: `UserEndpointsSpec` specs are not been executed
Firstable, excellent job with this sort of toy/teaching project. I love it! 🙌

Having said that, I can go  straight to bussiness😁

I noticed none of the `UserEndpointsSpec` specs are been executed. If you take a closer look [here](https://github.com/pauljamescleary/scala-pet-store/blob/066489e8ba40ea76ae397fb0b5842e101775ada3/src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala#L35-L43), the for comprehension corresponds to an `IO[Assertion]` computation which never gets executed.  That actually doesn't happen in the rest of the endpoints specs, which execute the computation by calling `unsafeRunSync`.

I'm trying to push a PR fixing it but I'm getting two weird  `http4s-circe` decoding errors. I'm not sure why those are happening because standalone `circe` decodes both examples perfectly

Here are the errors:

1. The first one, if I use the arbitrary instance generation for `User` case class
```
InvalidMessageBodyFailure was thrown during property evaluation.
[info]     Message: Invalid message body: Could not decode JSON: {
[info]     "userName" : "",
[info]     "firstName" : "",
[info]     "lastName" : "",
[info]     "email" : "",
[info]     "hash" : "",
[info]     "phone" : "",
[info]     "id" : 1
[info]   }
[info]     Occurred when passed generated values (
[info]       arg0 = User(,,,,,,Some(1))
[info]     )
```
2. The second one, If I use the [user value](https://github.com/pauljamescleary/scala-pet-store/blob/066489e8ba40ea76ae397fb0b5842e101775ada3/src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala#L33) provided in the code
```
org.http4s.InvalidMessageBodyFailure: Invalid message body: Could not decode JSON: {
[info]   "userName" : "username",
[info]   "firstName" : "firstname",
[info]   "lastName" : "lastname",
[info]   "email" : "email",
[info]   "hash" : "password",
[info]   "phone" : "phone",
[info]   "id" : null
[info] }
[info]   at org.http4s.circe.CirceInstances.$anonfun$jsonOf$2(CirceInstances.scala:55)
[info]   at scala.util.Either.fold(Either.scala:189)
[info]   at org.http4s.circe.CirceInstances.$anonfun$jsonOf$1(CirceInstances.scala:56)
[info]   at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:87)
[info]   at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:207)
[info]   at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:207)
[info]   at cats.effect.IO.unsafeRunTimed(IO.scala:304)
[info]   at cats.effect.IO.unsafeRunSync(IO.scala:239)
[info]   at io.github.pauljamescleary.petstore.infrastructure.endpoint.UserEndpointsSpec.$anonfun$new$1(UserEndpointsSpec.scala:37)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   ...
[info]   Cause: io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(password)
```

I think someone else ran into the first issue before. He must have tried to fix it using a fixed value for the `User` case class but forgot to execute the computation and therefore the spec turned successful when it was actually broken. All this is just speculation on my end.

I'll take a closer look at `http4s-circe` code later to check if I can spot the issue. Meanwhile, if someone has a clue on this I'll be glad to listen/reading about it in order to fix the issue.

### PR DESCRIPTION
**Pull request by nebtrx**
This fixes the issues explained in #91 by executing the assertion computation and fixing the decoding trouble, which vanished after passing a `SignupRequest` value to the  `createRequest ` instead of a `User` one.

Additionally, this fixes some other minor issues inside the specs. I'll leave some comments addressing those

Let me know if this useful. Otherwise, feel free to make suggestions so we can improve it.

Cheers 🍻

### CODE REVIEW

File: src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/UserRepositoryInMemoryInterpreter.scala [hunk 1]
```diff
@@ -31,7 +31,7 @@ class UserRepositoryInMemoryInterpreter[F[_]: Applicative] extends UserRepositor
   def delete(id: Long): F[Option[User]] = cache.remove(id).pure[F]
 
   def findByUserName(userName: String): F[Option[User]] =
-    cache.values.find(u => u.firstName == userName).pure[F]
```
Comment (nebtrx) [inline src/main/scala/io/github/pauljamescleary/petstore/infrastructure/repository/inmemory/UserRepositoryInMemoryInterpreter.scala]: This was causing the `findByUserName` spec to fail

File: src/test/scala/io/github/pauljamescleary/petstore/Arbitraries.scala [hunk 2]
```diff
@@ -14,6 +15,9 @@ import io.github.pauljamescleary.petstore.domain.users._
 
 trait PetStoreArbitraries {
 
+  val userNameLength = 16
+  val userNameGen: Gen[String] = Gen.listOfN(userNameLength, Gen.alphaChar).map(_.mkString)
```
Comment (nebtrx) [inline src/test/scala/io/github/pauljamescleary/petstore/Arbitraries.scala]: I took the liberty of creating a username generator because the specs were failing for too large username or usernames containing some Asian characters(probably UTF-16 encoding). 

I kept things simple, 16 alpha characters, since this is only for test purposes but, let me know if you'd like to consider more complex scenarios for the username generator

File: src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala [hunk 3]
```diff
@@ -82,24 +83,24 @@ class UserEndpointsSpec
...
-      createdUser.userName shouldEqual getUser.userName
+    forAll { userSignup: SignupRequest =>
+      (for {
+        createRequest <- Request[IO](Method.POST, Uri.uri("/users"))
+          .withBody(userSignup.asJson)
+        createResponse <- userHttpService
+          .run(createRequest)
+          .getOrElse(fail(s"Request was not handled: $createRequest"))
+        createdUser <- createResponse.as[User]
+        getRequest = Request[IO](Method.GET, Uri.unsafeFromString(s"/users/${createdUser.userName}"))
```
Comment (nebtrx) [inline src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala]: I also took the liberty of extracting out a couple of requests here ..

File: src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala [hunk 4]
```diff
@@ -111,25 +112,27 @@ class UserEndpointsSpec
...
-      getResponse.status shouldEqual NotFound
+    forAll { userSignup: SignupRequest =>
+      (for {
+        createRequest <- Request[IO](Method.POST, Uri.uri("/users"))
+          .withBody(userSignup.asJson)
+        createResponse <- userHttpService
+          .run(createRequest)
+          .getOrElse(fail(s"Request was not handled: $createRequest"))
+        createdUser <- createResponse.as[User]
+        deleteRequest = Request[IO](Method.DELETE, Uri.unsafeFromString(s"/users/${createdUser.userName}"))
```
Comment (nebtrx) [inline src/test/scala/io/github/pauljamescleary/petstore/infrastructure/endpoint/UserEndpointsSpec.scala]: and  here

**Comment by pauljamescleary** [comment]
Good here, can I merge?

Also, I did not add you in AUTHORS, feel free to open a PR for that (or I can add you)

**Comment by nebtrx** [comment]
I think it's ready to be merged if you don't have any further suggestions. As for the AUTHORS, I'll push a PR later for that. That way I'll save a little bit of your time 😉

**Comment by pauljamescleary** [comment]
This is great, thank you very much @nebtrx !!!

**Comment by pauljamescleary** [comment]
Closes #91

**Comment by nebtrx** [comment]
@paulcleary thanks to you for such a great idea with this repo.
